### ISSUE TITLE
I want to autogenerate query using the graphql query generator and provide only schema to get openapi spec

### ISSUE THREAD

**Issue by imranshaik012** [schwer/graphql-to-openapi#67]
**Is your feature request related to a problem? Please describe.**
I want to autogenerate Graphql Query 

**Describe the solution you'd like**
The solution to auto generate Graphql Query is using this library https://github.com/IBM/graphql-query-generator

**Describe alternatives you've considered**
Or using any other Graphql query generator

**Additional context**
I want to provide only graphql schema and take the graphql query from Autogenerated query library and convert it to OpenAPI spec.

**Comment by schwer** [comment]
Can you give a little more detail in what you desire? The library usage should already support any case where a graphql and schema are provided programmatically. The following is adapted from https://github.com/IBM/graphql-query-generator#minimal-working-example.

```
import { print, buildSchema } from 'graphql';
import { generateRandomQuery } from 'ibm-graphql-query-generator';

const schemaString = `
  type Query {
    getUser(name: String!): User
    .....
}
`;

const configuration = {
  depthProbability: 0.5,
  breadthProbability: 0.5,
  providerMap: {
  ....
}

const { queryDocument, variableValues, seed } = generateRandomQuery(
  buildSchema(schemaString),
  configuration
);

const { openApiSchema } = graphqlToOpenApi({
  schemaString,
  inputQuery: print(queryDocument)
});

```

A more performant version is possible, avoiding the excess re-parsing of the schema, but would require more tinkering.

**Comment by schwer** [comment]
How do you envision generating a single graphql query from only the schema?

**Comment by schwer** [comment]
I gave this a little more thought, the only means I can think of is to make some assumptions about top level queries and mutations mapping to openapi endpoints. Not sure if those assumptions are going to work as a general purpose tool like graphql-to-openapi intends to be.
