### ISSUE TITLE
No Inline Fragment Implementation

### ISSUE THREAD

**Issue by kadenlalani7** [schwer/graphql-to-openapi#90]
**Describe the bug**
Cannot convert any queries containing a graphql inline fragment 

**To Reproduce**
1. Use the tool given the query contains an inline fragment

**Expected behavior**
You will receive an error, saying   Cannot read property 'push' of undefined.
This is not what we want.

**Screenshots**
![image](https://user-images.githubusercontent.com/33525785/126813839-8794e429-76a3-4599-8a2e-d1b740651736.png)

**Comment by schwer** [comment]
@kadenlalani7 Any chance you can provide the input schema and query that caused the error?
